language: java
jdk:
- oraclejdk8
before_install:
- chmod +x mvnw
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  sonarcloud:
    organization: "dcorteztec-github"
    token:
      secure: $SONAR_TOKEN
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
- mvn package
- mvn test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  app: dangerareaservice
  api_key: $HEROKU_TOKEN
  on:
     repo: dcorteztec/dangerAreaService
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
